<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net472;net10.0-windows</TargetFrameworks>
		<OutputType>WinExe</OutputType>
		<AssemblyName>NucleusCoop</AssemblyName>
		<SccProjectName></SccProjectName>
		<SccLocalPath></SccLocalPath>
		<SccAuxPath></SccAuxPath>
		<SccProvider></SccProvider>
		<IsWebBootstrapper>false</IsWebBootstrapper>
		<SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\</SolutionDir>
		<RestorePackages>true</RestorePackages>
		<PublishUrl>publish\</PublishUrl>
		<Install>true</Install>
		<InstallFrom>Disk</InstallFrom>
		<UpdateEnabled>false</UpdateEnabled>
		<UpdateMode>Foreground</UpdateMode>
		<UpdateInterval>7</UpdateInterval>
		<UpdateIntervalUnits>Days</UpdateIntervalUnits>
		<UpdatePeriodically>false</UpdatePeriodically>
		<UpdateRequired>false</UpdateRequired>
		<MapFileExtensions>true</MapFileExtensions>
		<ApplicationRevision>0</ApplicationRevision>
		<ApplicationVersion>1.0.0.%2a</ApplicationVersion>
		<UseApplicationTrust>false</UseApplicationTrust>
		<BootstrapperEnabled>true</BootstrapperEnabled>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<UseWindowsForms>true</UseWindowsForms>
		<UseWPF>true</UseWPF>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Configurations>Debug;Release;SaveEdit Packaging;TestDebug</Configurations>
		<EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
		<Platforms>AnyCPU;x86</Platforms>
	</PropertyGroup>
	<PropertyGroup>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>
	<PropertyGroup>
		<AssemblyOriginatorKeyFile>SplitKey.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>
	<PropertyGroup>
		<ApplicationIcon>icon.ico</ApplicationIcon>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
		<DefineConstants>TRACE;DEBUG;ALPHA</DefineConstants>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
	  <DefineConstants>TRACE;DEBUG;ALPHA</DefineConstants>
	  <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
		<DefineConstants>TRACE;ALPHA</DefineConstants>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
		<UseVSHostingProcess>true</UseVSHostingProcess>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
	  <DefineConstants>TRACE;ALPHA</DefineConstants>
	  <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
	  <UseVSHostingProcess>true</UseVSHostingProcess>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'TestDebug|AnyCPU'">
		<OutputPath>bin\TestDebug\</OutputPath>
		<DefineConstants>TRACE;DEBUG;TEST</DefineConstants>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='TestDebug|x86'">
	  <OutputPath>bin\TestDebug\</OutputPath>
	  <DefineConstants>TRACE;DEBUG;TEST</DefineConstants>
	  <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup>
		<RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
	</PropertyGroup>
	<PropertyGroup>
		<StartupObject></StartupObject>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'TestDebug|Win32'">
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="Microsoft.VisualBasic" />
		<Reference Include="System.ComponentModel.Composition" />
		<Reference Include="System.Design" />
		<Reference Include="System.Management" />
		<Reference Include="System.Data.DataSetExtensions" />
		<Reference Include="Microsoft.CSharp" />
	</ItemGroup>
	<ItemGroup>
		<Compile Update="Controls\HandlerNotesZoom.cs">
			<SubType>Component</SubType>
		</Compile>
		<Compile Update="Controls\HubButton.cs">
			<SubType>Component</SubType>
		</Compile>
		<Compile Update="Controls\CustomCheckBox.cs">
			<SubType>Component</SubType>
		</Compile>
		<Compile Update="Controls\CustomRadio.cs">
			<SubType>Component</SubType>
		</Compile>
		<Compile Update="Controls\CustomSwitch.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\FlatCombo.cs">
			<SubType>Component</SubType>
		</Compile>
		<Compile Update="Controls\FlatTextBox.cs">
			<SubType>Component</SubType>
		</Compile>
		<Compile Update="Controls\HubWebView.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\PlaytimePanel.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\ProfilesList.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\SearchTextBox.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\SortOptionsPanel.cs">
			<SubType>Component</SubType>
		</Compile>
		<Compile Update="Controls\SortGamesButton.cs">
			<SubType>Component</SubType>
		</Compile>
		<Compile Update="Controls\ToggleFavoriteButton.cs">
			<SubType>Component</SubType>
		</Compile>
		<Compile Update="Controls\Tutorial.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Properties\Resources.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Resources.resx</DependentUpon>
		</Compile>
		<Compile Update="Properties\Settings.Designer.cs">
		  <DesignTimeSharedInput>True</DesignTimeSharedInput>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Settings.settings</DependentUpon>
		</Compile>
		<None Update="app.manifest">
			<SubType>Designer</SubType>
		</None>
		<None Update="gui\theme\default\theme.ini">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Properties\Settings.settings">
		  <Generator>SettingsSingleFileGenerator</Generator>
		  <LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\NucleusGaming\Nucleus.Gaming.csproj" />
		<ProjectReference Include="..\StartGame\Nucleus.Coop.StartGame.csproj" />
		<ProjectReference Include="..\ThirdParty\WindowScrape\WindowScrape.csproj" />
	</ItemGroup>
	<ItemGroup>
		<BootstrapperPackage Include=".NETFramework,Version=v4.0,Profile=Client">
			<Visible>False</Visible>
			<ProductName>Microsoft .NET Framework 4 Client Profile %28x86 and x64%29</ProductName>
			<Install>true</Install>
		</BootstrapperPackage>
		<BootstrapperPackage Include="Microsoft.Net.Client.3.5">
			<Visible>False</Visible>
			<ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
			<Install>false</Install>
		</BootstrapperPackage>
		<BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
			<Visible>False</Visible>
			<ProductName>.NET Framework 3.5 SP1</ProductName>
			<Install>false</Install>
		</BootstrapperPackage>
		<BootstrapperPackage Include="Microsoft.Windows.Installer.4.5">
			<Visible>False</Visible>
			<ProductName>Windows Installer 4.5</ProductName>
			<Install>true</Install>
		</BootstrapperPackage>
	</ItemGroup>
	<ItemGroup>
		<Content Include="copyoutput\SDL2.dll" />
		<Content Include="Resources\xboxControllerFront.png" />
		<Content Include="copyoutput\openxinput1_3.dll" />
		<Content Include="gui\icons\default.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\16players.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\2horizontal.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\2vertical.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\4players.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\6players.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\8players.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\add_game.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\arrow_left.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\arrow_left_mousehover.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\arrow_right.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\arrow_right_mousehover.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\audio.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\buttons_dropdown.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\click.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\cursor.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\cursor_hand.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\donation.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\expand_Notes.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\extract_nc.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\extract_nc_mousehover.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\favorite_selected.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\favorite_unselected.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\background.jpg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\cover_layer.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\customLayout.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\dinput.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\dinput_icon.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\fullscreen.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\b1.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\b2.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\b3.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\b4.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\dd.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\dl.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\dn.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\dr.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\du.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\h.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\lb.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\ls.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\lsc.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\lse.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\lsn.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\lsnsew.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\lss.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\lsw.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\lt.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\rb.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\rs.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\rsc.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\rse.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\rsn.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\rsnsew.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\rss.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\rsw.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\rt.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\select.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Playstation\start.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\b1.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\b2.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\b3.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\b4.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\dd.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\dl.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\dn.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\dr.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\du.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\h.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\lb.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\ls.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\lsc.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\lse.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\lsn.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\lsnsew.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\lss.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\lsw.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\lt.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\rb.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\rs.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\rsc.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\rse.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\rsn.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\rsnsew.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\rss.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\rsw.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\rt.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\select.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\gamepads\Xbox\start.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\game_options.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\home.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\instruction_closed.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\instruction_opened.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\keyboard.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\keyboard_icon.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\layout.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\loading.gif">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\locked.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\log.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\log_mousehover.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\magnifier.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\magnifier_close.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\manualLayout.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\page1.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\page2.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\play.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\players.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\profile_info.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\profile_info_mousehover.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\profile_settings.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\processor.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\profiles_list.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\proto_keyboard.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\proto_mouse.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\refresh.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\screen.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\logo.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\no_cover.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\other_backgrounds.jpg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\search_game.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\search_game_mousehover.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\shared.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\title_close.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\title_close_mousehover.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\title_download_assets.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\title_download_assets_mousehover.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\title_dropdown_closed.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\title_dropdown_opened.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\title_logo.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\title_maximize.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\title_maximize_mousehover.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\title_minimize.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\title_minimize_mousehover.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\title_no_hub.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\title_settings.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\title_settings_mousehover.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\title_windowed.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\title_windowed_mousehover.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\unlocked.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\update.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\xinput_background.jpg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\xinput.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\theme\default\xinput_icon.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="gui\tutorial\tutorial.gif">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="icon.ico" />
		<Content Include="Resources\icon.ico" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="DotNetZip.Reduced" Version="1.9.1.8" />
		<PackageReference Include="Microsoft.NETCore.Platforms" Version="7.0.2" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2210.55" />
		<PackageReference Include="Microsoft.Win32.Primitives" Version="4.3.0" />
		<PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
		<PackageReference Include="NAudio" Version="1.10.0" />
		<PackageReference Include="NETStandard.Library" Version="2.0.3" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="SharpDX" Version="4.2.0" />
		<PackageReference Include="SharpDX.DirectInput" Version="4.2.0" />
		<PackageReference Include="SharpDX.XInput" Version="4.2.0" />
		<PackageReference Include="System.AppContext" Version="4.3.0" />
		<PackageReference Include="System.Collections" Version="4.3.0" />
		<PackageReference Include="System.Collections.Concurrent" Version="4.3.0" />
		<PackageReference Include="System.Console" Version="4.3.1" />
		<PackageReference Include="System.Diagnostics.Debug" Version="4.3.0" />
		<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="7.0.2" />
		<PackageReference Include="System.Diagnostics.Tools" Version="4.3.0" />
		<PackageReference Include="System.Diagnostics.Tracing" Version="4.3.0" />
		<PackageReference Include="System.Globalization" Version="4.3.0" />
		<PackageReference Include="System.Globalization.Calendars" Version="4.3.0" />
		<PackageReference Include="System.IO" Version="4.3.0" />
		<PackageReference Include="System.IO.Compression" Version="4.3.0" />
		<PackageReference Include="System.IO.Compression.ZipFile" Version="4.3.0" />
		<PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
		<PackageReference Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
		<PackageReference Include="System.Linq" Version="4.3.0" />
		<PackageReference Include="System.Linq.Expressions" Version="4.3.0" />
		<PackageReference Include="System.Net.Primitives" Version="4.3.1" />
		<PackageReference Include="System.Net.Sockets" Version="4.3.0" />
		<PackageReference Include="System.ObjectModel" Version="4.3.0" />
		<PackageReference Include="System.Reflection" Version="4.3.0" />
		<PackageReference Include="System.Reflection.Extensions" Version="4.3.0" />
		<PackageReference Include="System.Reflection.Primitives" Version="4.3.0" />
		<PackageReference Include="System.Resources.ResourceManager" Version="4.3.0" />
		<PackageReference Include="System.Runtime" Version="4.3.1" />
		<PackageReference Include="System.Runtime.Extensions" Version="4.3.1" />
		<PackageReference Include="System.Runtime.Handles" Version="4.3.0" />
		<PackageReference Include="System.Runtime.InteropServices" Version="4.3.0" />
		<PackageReference Include="System.Runtime.InteropServices.RuntimeInformation" Version="4.3.0" />
		<PackageReference Include="System.Runtime.Numerics" Version="4.3.0" />
		<PackageReference Include="System.Security.AccessControl" Version="6.0.0" />
		<PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
		<PackageReference Include="System.Security.Cryptography.Encoding" Version="4.3.0" />
		<PackageReference Include="System.Security.Cryptography.Primitives" Version="4.3.0" />
		<PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" />
		<PackageReference Include="System.Security.Principal.Windows" Version="5.0.0" />
		<PackageReference Include="System.Text.Encoding" Version="4.3.0" />
		<PackageReference Include="System.Text.Encoding.Extensions" Version="4.3.0" />
		<PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
		<PackageReference Include="System.Threading" Version="4.3.0" />
		<PackageReference Include="System.Threading.Tasks" Version="4.3.0" />
		<PackageReference Include="System.Threading.Timer" Version="4.3.0" />
		<PackageReference Include="System.Xml.ReaderWriter" Version="4.3.1" />
		<PackageReference Include="System.Xml.XDocument" Version="4.3.0" />
	</ItemGroup>
	<PropertyGroup />
	<PropertyGroup />
	<ItemGroup>
		<None Visible="false" Include="$(SolutionDir)ThirdParty\easyhook\*.dll;$(SolutionDir)ThirdParty\easyhook\*.exe">
			<Link>%(FileName)%(Extension)</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Visible="false" Include="$(SolutionDir)ThirdParty\AutoHotkey.Interop\x64\*.dll">
			<Link>x64\%(FileName)%(Extension)</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Visible="false" Include="$(SolutionDir)ThirdParty\AutoHotkey.Interop\x86\*.dll">
			<Link>x86\%(FileName)%(Extension)</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Visible="false" Include="$(ProjectDir)copyoutput\**\*.*">
			<Link>%(RecursiveDir)%(FileName)%(Extension)</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<PropertyGroup>
		<UsePrebuiltProtoInput Condition="'$(UsePrebuiltProtoInput)' == ''">true</UsePrebuiltProtoInput>
	</PropertyGroup>
	<ItemGroup Condition="'$(UsePrebuiltProtoInput)' == 'true'">
		<None Visible="false" Include="$(SolutionDir)..\Submodules\ProtoInput\src\ProtoInput\Release\*.dll">
			<Link>%(FileName)%(Extension)</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Update="Properties\Resources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="echo. &gt; &quot;$(TargetDir)Built.flag&quot;" />
	</Target>
	<ItemGroup>
		<Compile Remove="Controls\ExtractButton .cs" />
		<None Include="Controls\ExtractButton .cs" />
		<Compile Remove="Controls\ExtractButton .Designer.cs" />
		<None Include="Controls\ExtractButton .Designer.cs" />
		<Compile Remove="Controls\ExtractButton .resx" />
		<None Include="Controls\ExtractButton .resx" />

		<Compile Remove="Controls\SearchGameButton.cs" />
		<None Include="Controls\SearchGameButton.cs" />
		<Compile Remove="Controls\SearchGameButton.Designer.cs" />
		<None Include="Controls\SearchGameButton.Designer.cs" />
		<Compile Remove="Controls\SearchGameButton.resx" />
		<None Include="Controls\SearchGameButton.resx" />


		<Compile Remove="Controls\HubButton.Designer.cs" />
		<None Include="Controls\HubButton.Designer.cs" />
		
		<Compile Remove="Controls\RoundedButton.cs" />
		<None Include="Controls\RoundedButton.cs" />
	</ItemGroup>
</Project>