<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<TargetFrameworks>net472;net10.0-windows</TargetFrameworks>
		<OutputType>Library</OutputType>
		<SccProjectName></SccProjectName>
		<SccLocalPath></SccLocalPath>
		<SccAuxPath></SccAuxPath>
		<SccProvider></SccProvider>
		<SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\</SolutionDir>
		<RestorePackages>true</RestorePackages>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<UseWindowsForms>true</UseWindowsForms>
		<UseWPF>true</UseWPF>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<Configurations>Debug;Release;SaveEdit Packaging;TestDebug</Configurations>
	</PropertyGroup>
	<PropertyGroup>
		<SignAssembly>true</SignAssembly>
	</PropertyGroup>
	<PropertyGroup>
		<AssemblyOriginatorKeyFile>GamingKey.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
		<DefineConstants>TRACE;DEBUG;UNSAFE;ALPHA</DefineConstants>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
		<OutputPath>bin\Release\bin\</OutputPath>
		<DefineConstants>TRACE;UNSAFE;ALPHA;RELEASE</DefineConstants>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
		<DebugSymbols>true</DebugSymbols>
		<UseVSHostingProcess>true</UseVSHostingProcess>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'TestDebug|AnyCPU'">
		<OutputPath>bin\TestDebug\</OutputPath>
		<DefineConstants>UNSAFE</DefineConstants>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="EasyHook">
			<HintPath>..\ThirdParty\easyhook\EasyHook.dll</HintPath>
		</Reference>
		<Reference Include="System.ComponentModel.Composition" />
		<Reference Include="System.Design" />
		<Reference Include="System.DirectoryServices.AccountManagement" />
		<Reference Include="System.IO.Compression" />
		<Reference Include="System.Management" />
		<Reference Include="System.Runtime.Remoting" />
		<Reference Include="System.Data.DataSetExtensions" />
		<Reference Include="Microsoft.CSharp" />
	</ItemGroup>
	<ItemGroup>
		<Compile Update="Controls\DoubleBufferPanel.cs">
			<SubType>Component</SubType>
		</Compile>
		<Compile Update="Controls\BufferedFlowLayoutPanel.cs">
			<SubType>Component</SubType>
		</Compile>
		<Compile Update="Controls\GameControl.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\HorizontalGameControl.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\HorizontalControlListBox.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\TransparentRichTextBox.cs">
			<SubType>Component</SubType>
		</Compile>
		<Compile Update="Controls\BorderPanel.cs">
			<SubType>Component</SubType>
		</Compile>
		<Compile Update="Controls\ControlListBox.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\CoolCheckbox.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\CoolListControl.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\CustomComboBox.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\PictureButton.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\SizeableCheckbox.cs">
			<SubType>Component</SubType>
		</Compile>
		<Compile Update="Controls\CustomNumericUpDown.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\JSUserInputControl.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\ImageButton.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\UserInputControl.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\PlayerCountControl.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\PlayerOptionsControl.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Controls\SetupScreen\SetupScreenControl.cs">
			<SubType>UserControl</SubType>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\ThirdParty\WindowScrape\WindowScrape.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="Resources\icon.ico" />
		<Content Include="Resources\xinput1_3.dll" />
	</ItemGroup>
	<ItemGroup>
		<WCFMetadata Include="Connected Services\" />
	</ItemGroup>
	<ItemGroup>
		<COMReference Include="IWshRuntimeLibrary">
			<Guid>{F935DC20-1CF0-11D0-ADB9-00C04FD58A0B}</Guid>
			<VersionMajor>1</VersionMajor>
			<VersionMinor>0</VersionMinor>
			<Lcid>0</Lcid>
			<WrapperTool>tlbimp</WrapperTool>
			<Isolated>False</Isolated>
			<EmbedInteropTypes>True</EmbedInteropTypes>
		</COMReference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="DotNetZip.Reduced" Version="1.9.1.8" />
		<PackageReference Include="Jint" Version="2.11.58" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="SharpDX" Version="4.2.0" />
		<PackageReference Include="SharpDX.DirectInput" Version="4.2.0" />
		<PackageReference Include="SharpDX.XInput" Version="4.2.0" />
		<PackageReference Include="System.Runtime" Version="4.3.1" />
	</ItemGroup>
	<PropertyGroup />
	<ItemGroup>
		<Compile Remove="Controls\CustomCheckBox.cs" />
		<None Include="Controls\CustomCheckBox.cs" />

		<Compile Remove="Forms\WPf_DivForm.xaml.cs" />
		<None Include="Forms\WPf_DivForm.xaml.cs" />

		<Compile Remove="Forms\WPF_OSD.xaml.cs" />
		<None Include="Forms\WPF_OSD.xaml.cs" />
		
		<Compile Remove="Tools\Steamless\Steamless.cs" />
		<None Include="Tools\Steamless\Steamless.cs" />

		<Compile Remove="Tools\SteamStubDRMPatcher\SteamStubDRMPatcher.cs" />
		<None Include="Tools\SteamStubDRMPatcher\SteamStubDRMPatcher.cs" />
		
		<Compile Remove="Util\FirewallUtil.cs" />
		<None Include="Util\FirewallUtil.cs" />
		
		<Compile Remove="Util\FolderUtil.cs" />
		<None Include="Util\FolderUtil.cs" />
		
		<Compile Remove="Util\NetworkUtil.cs" />
		<None Include="Util\NetworkUtil.cs" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
		<PackageReference Include="System.Management" Version="10.0.2" />
		<PackageReference Include="System.DirectoryServices.AccountManagement" Version="10.0.2" />
		<PackageReference Include="System.DirectoryServices" Version="10.0.2" />
		<PackageReference Include="EasyHook" Version="2.7.7097" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net472'">
		<Reference Include="EasyHook">
			<HintPath>..\ThirdParty\easyhook\EasyHook.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>