<Project>
	<PropertyGroup>
		<BaseOutputPath>$(MSBuildThisFileDirectory)NucleusCoopTool\bin\</BaseOutputPath>
		<OutputPath>$(BaseOutputPath)\$(Configuration)\</OutputPath>

		<AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>true</AppendRuntimeIdentifierToOutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.vcxproj'">
		<OutDir>$(BaseOutputPath)\$(Configuration)\native\</OutDir>
	</PropertyGroup>
</Project>